server:
  port: 8101

spring:
  application:
    name: springcloud_stu

#日志输出
logging:
  level:
    org.springframework.web: info
    #com.asx717.openapi.dao: debug       #指定包日志输出，实现mybatis输出日志
  file:
    path: logs/springcloud_stu
